# 
#   docker-compose.yml: definición de los contenedores del proyecto
#
#   Referencia: https://github.com/FIWARE/tutorials.Step-by-Step
#
version: "3.8"
services:
  # Orion is the context broker
  orion:
    labels:
      com.wordpress.fcosfc: 'fiware-iot-upo'
    image: fiware/orion:${ORION_VERSION}
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    networks:
      - default
    ports:
      - "${ORION_PORT}:${ORION_PORT}" # localhost:1026
    command: -dbhost mongo-db -logLevel DEBUG -noCache
    healthcheck:
      test: curl --fail -s http://orion:${ORION_PORT}/version || exit 1
      interval: 5s


  # Databases
  mongo-db:
    labels:
      com.wordpress.fcosfc: 'fiware-iot-upo'
    image: mongo:${MONGO_DB_VERSION}
    hostname: mongo-db
    container_name: db-mongo
    expose:
      - "${MONGO_DB_PORT}"
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}" # localhost:27017 # localhost:27017
    networks:
      - default
    volumes:
      - mongo-db:/data
    healthcheck:
      test: |
        host=`hostname --ip-address || echo '127.0.0.1'`; 
        mongo --quiet $host/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' && echo 0 || echo 1
      interval: 5s

  # Other services
  mosquitto:
    labels:
      com.wordpress.fcosfc: 'fiware-iot-upo'
    image: eclipse-mosquitto:${MOSQUITTO_VERSION}
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "${MOSQUITTO_PORT}"
    ports:
      - "${MOSQUITTO_PORT}:${MOSQUITTO_PORT}"
    volumes:
      - ./provisioning/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - default

networks:
  default:
    labels:
      com.wordpress.fcosfc: 'fiware-iot-upo'
    ipam:
      config:
        - subnet: 172.18.1.0/24

volumes:
  mongo-db: ~
